apiVersion: v2
name: outline
description: A Helm chart for https://github.com/outline/outline
type: application
version: 0.3.1
appVersion: 0.65.2
dependencies:
  - name: redis
    version: 24.1.0
    repository: oci://registry-1.docker.io/bitnamicharts
maintainers:
  - name: Qiong Wu
    email: qiong.wu@gfnork.de
sources:
  - https://github.com/gfnork/outline-helm
